version: "3.2"
services:
    db:
      container_name: db
      restart: always
      image: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_USER: "sms"
        MYSQL_PASSWORD: "sms"
        MYSQL_DATABASE: "sms"
      volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - ./data/db:/var/lib/mysql
      networks:
        - nat

    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - 8003:80      
      depends_on:
        - db
      networks:
        - nat

networks:
  nat: